---
- name: 'GPU passthrough | NOOP'
  ansible.builtin.debug:
    msg: 'GPU passthrough currently disabled until migrated'

# TODO(role): migrate original passthrough and re-enable.
- name: 'GPU passthrough | nvidia guest'
  when: >
    debian_gpu_brand | lower == 'nvidia' and
    debian_gpu_passthrough_mode | lower == 'guest'
  ansible.builtin.include_tasks: 'nvidia_guest.yml'

- name: 'GPU passthrough | nvidia host'
  when: >
    debian_gpu_brand | lower == 'nvidia' and
    debian_gpu_passthrough_mode | lower == 'host'
  ansible.builtin.include_tasks: 'nvidia_host.yml'

- name: 'GPU passthrough | amd guest'
  when: >
    debian_gpu_brand | lower == 'amd' and
    debian_gpu_passthrough_mode | lower == 'guest'
  ansible.builtin.include_tasks: 'amd_guest.yml'

- name: 'GPU passthrough | amd host'
  when: >
    debian_gpu_brand | lower == 'amd' and
    debian_gpu_passthrough_mode | lower == 'host'
  ansible.builtin.include_tasks: 'amd_host.yml'
